name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath C:\Windows\System32
    
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
    
    - name: Create Tunnel
      run: |
        cd C:\Windows\System32
        ./ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"
        Start-Process C:\Windows\System32\ngrok.exe -ArgumentList "tcp 3389" -WindowStyle Hidden
    
    - name: Connect to RDP
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Runner@123" -Force)
        Start-Sleep -Seconds 10
        $connect = (Get-NetTCPConnection -LocalPort 4040).RemotePort
        If ($connect) {
            $tunnel = (Invoke-WebRequest -Uri http://localhost:4040/api/tunnels).Content | ConvertFrom-Json 
            $rdp = $tunnel.tunnels[0].public_url -replace "tcp://", "" 
            Write-Host "RDP Connection Details:"
            Write-Host "------------------------"
            Write-Host "Computer/Host: $rdp"
            Write-Host "Username: runneradmin"
            Write-Host "Password: Runner@123"
            Write-Host "------------------------"
        }
    
    - name: Keep Alive
      run: |
        $i = 0
        do {
          if ($i -eq 0) {
            $tunnel = (Invoke-WebRequest -Uri http://localhost:4040/api/tunnels).Content | ConvertFrom-Json 
            $rdp = $tunnel.tunnels[0].public_url -replace "tcp://", "" 
            Write-Host "`nRDP is ready! Connect using:"
            Write-Host "Computer/Host: $rdp"
            Write-Host "Username: runneradmin"
            Write-Host "Password: Runner@123"
          }
          Start-Sleep -Seconds 60
          $i++
          Write-Host "Session has been active for $i minute(s)"
        } while ($true)
